apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          ls -la
    needs:
      - checkout
  checkout:
    steps:
      - uses: cloudbees-io/checkout@v1
        with:
          provider: github
          repository: andreasgrob/casc-bundle-rendering
