apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Bundle Rendering
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Checkout main
        uses: cloudbees-io/checkout@v1
        with:
          path: main
      - name: Checkout effective
        uses: cloudbees-io/checkout@v1
        with:
          path: effective
          ref: effective
      - name: Render Bundles
        uses: docker://alpine:3.18.4
        run: |
          rm -rf effective/*
          cp -r main/* effective/
          cd effective
          for d in */ ; do
            if [ "$d" == "base/" ] ; then
              continue
            fi
            cp -r base/* $d
            mkdir -p $d/plugin-catalog
          done
          rm -rf base
          chown -R 1000:1001 effective
      - name: Calculate Plugin Dependencies
        uses: docker://ghcr.io/kyounger/casc-plugin-dependency-calculation:v3.2.1
        run: |
          cd effective
          ls -la team/plugin-catalog
          /home/casc-user/run.sh -t mm -v 2.414.3.8 -f team/plugins/plugins.yaml \
                                                    -F team/plugins/plugins.yaml \
                                                    -c team/plugin-catalog/plugin-catalog.yaml
      - name: Commit and Push
        uses: docker://bitnami/git:2.42.0
        run: |
          git config --global user.name "Bundle Rendering"
          git config --global user.email "91457104+andreasgrob@users.noreply.github.com"
          cd effective
          git add .
          git diff-index --quiet HEAD || git commit -m "Render bundles from $GITHUB_SHA"
          git push
